### ISSUE TITLE
Bug 🐞: Can't run @nrwl/react component generator

### ISSUE THREAD

**Issue by shaharkazaz** [etkachev/nx-webstorm#76]
## Current Behavior
Can't run the command.

## How to Reproduce
Try and run the command via the plugin

## Envirounment: 
  Node : 12.20.0
  OS   : darwin x64 (MacOS Big Sur)
  Webstorm: 2021.2.3
  npm  : 7.24.1
  
  nx : 13.0.2
  @nrwl/angular : Not Found
  @nrwl/cli : 13.0.2
  @nrwl/cypress : 13.0.2
  @nrwl/devkit : 13.0.2
  @nrwl/eslint-plugin-nx : 13.0.2
  @nrwl/express : Not Found
  @nrwl/jest : 13.0.2
  @nrwl/linter : 13.0.2
  @nrwl/nest : Not Found
  @nrwl/next : Not Found
  @nrwl/node : Not Found
  @nrwl/nx-cloud : Not Found
  @nrwl/react : 13.0.2
  @nrwl/schematics : Not Found
  @nrwl/tao : 13.0.2
  @nrwl/web : 13.0.2
  @nrwl/workspace : 13.0.2
  @nrwl/storybook : 13.0.2
  @nrwl/gatsby : Not Found
  typescript : 4.3.5

## Additional context
The error stack:
```
java.lang.NullPointerException
	at com.github.etkachev.nxwebstorm.services.MyProjectService.getProjects(MyProjectService.kt:162)
	at com.github.etkachev.nxwebstorm.services.MyProjectService.getProjectList(MyProjectService.kt:84)
	at com.github.etkachev.nxwebstorm.utils.GenerateFormControl.<init>(GenerateFormControl.kt:20)
	at com.github.etkachev.nxwebstorm.ui.RunSchematicPanel.<init>(RunSchematicPanel.kt:42)
	at com.github.etkachev.nxwebstorm.actionlisteners.SchematicSelectionTabListener.runSelectedLogic(SchematicSelectionTabListener.kt:139)
	at com.github.etkachev.nxwebstorm.actionlisteners.SchematicSelectionTabListener.valueChanged$lambda-2(SchematicSelectionTabListener.kt:125)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:776)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:746)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:885)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:754)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$6(IdeEventQueue.java:441)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:825)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$7(IdeEventQueue.java:440)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:794)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:492)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
```

**Comment by etkachev** [comment]
Yup I believe this has to do with the recent Nx 13 upgrade. Since all the nx.json does not have `projects` in there anymore. All `projects` are now declared in the `workspace.json` or `angular.json`. I will have a fix for this shortly.

**Comment by elicul** [comment]
Thank you @etkachev. If you need any help in testing just ping me.

**Comment by etkachev** [comment]
[nx-webstorm - 0.9.1.zip](https://github.com/etkachev/nx-webstorm/files/7448123/nx-webstorm.-.0.9.1.zip)

Can you guys give this a try? You will have to manually install the plugin. Let me know. Thanks!

**Comment by Yanduz** [comment]
@etkachev Great, it works! Thanks 👍 (Angular Project)

**Comment by elicul** [comment]
@etkachev works great! Thank you!

**Comment by etkachev** [comment]
Awesome. I published the fix to jetbrains. Might be a few days before they approve it and release it to marketplace.

**Comment by etkachev** [comment]
latest 0.9.1 is available for update. Let me know if there is anything else that comes up. Thanks!

**Comment by shaharkazaz** [comment]
@etkachev This works, but only if I'm working with per-project configuration.
I think you should still support getting the values from the `angular.json`
Thanks for the fix 🙂

**Comment by etkachev** [comment]
@shaharkazaz are you referring to when your project is setup with the `project.json` files? That it doesn't work? Like mentioned here in the [docs](https://nx.dev/l/r/core-concepts/configuration#workspacejson-and-projectjson)

**Comment by shaharkazaz** [comment]
@etkachev It was a bug on my end, the project I was trying to execute the commands on wasn't listed correctly. sorry for the noise 🙂
